import React, { useState, useEffect } from 'react';
import { Outfit, ActiveTab } from '../types/fashion';
import { fetchStyleRecommendations } from '../services/api';
import { Wand2, Sparkles, Sliders, CheckCircle2, ArrowRight, Palette, Tag } from 'lucide-react';

interface StyleRecommendationsProps {
  setActiveTab: (tab: ActiveTab) => void;
}

export const StyleRecommendations: React.FC<StyleRecommendationsProps> = ({ setActiveTab }) => {
  const [selectedStyle, setSelectedStyle] = useState<string>('all');
  const [selectedOccasion, setSelectedOccasion] = useState<string>('All');
  const [recommendations, setRecommendations] = useState<Outfit[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(false);

  useEffect(() => {
    setIsLoading(true);
    fetchStyleRecommendations({ category: selectedOccasion, style: selectedStyle }).then(data => {
      setRecommendations(data);
      setIsLoading(false);
    });
  }, [selectedOccasion, selectedStyle]);

  return (
    <section className="py-12 px-4 lg:px-8 max-w-7xl mx-auto space-y-10">
      
      {/* Header */}
      <div className="text-center max-w-3xl mx-auto space-y-3">
        <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full glass-card border border-rose-500/30 text-xs font-semibold text-rose-300">
          <Wand2 className="w-3.5 h-3.5 text-rose-400" />
          <span>Machine Learning Style Recommender</span>
        </div>
        <h2 className="font-serif text-3xl sm:text-4xl font-bold text-white">
          Personalized <span className="gradient-text">Style Studio</span>
        </h2>
        <p className="text-sm text-slate-300">
          Curated outfit recommendations generated by ML preference vector matching, color season harmony, and occasion tailoring.
        </p>
      </div>

      {/* Control Panel Filters */}
      <div className="glass-card rounded-2xl p-6 border border-white/10 grid grid-cols-1 md:grid-cols-2 gap-6">
        
        {/* Style Archetype Filter */}
        <div className="space-y-2">
          <label className="text-xs font-semibold text-slate-300 flex items-center gap-2">
            <Tag className="w-4 h-4 text-violet-400" />
            <span>Select Style Archetype</span>
          </label>
          <div className="flex flex-wrap gap-2">
            {[
              { id: 'all', label: 'All Styles' },
              { id: 'minimalist', label: 'Quiet Luxury' },
              { id: 'elegant', label: 'Executive Power' },
              { id: 'evening', label: 'Evening Glamour' },
              { id: 'streetwear', label: 'Urban Streetwear' }
            ].map(item => (
              <button
                key={item.id}
                onClick={() => setSelectedStyle(item.id)}
                className={`px-3.5 py-1.5 rounded-lg text-xs font-medium transition-all ${
                  selectedStyle === item.id
                    ? 'bg-gradient-to-r from-violet-600 to-rose-500 text-white font-bold shadow-md shadow-violet-600/30'
                    : 'bg-slate-900/60 text-slate-400 hover:text-white hover:bg-slate-800'
                }`}
              >
                {item.label}
              </button>
            ))}
          </div>
        </div>

        {/* Occasion Filter */}
        <div className="space-y-2">
          <label className="text-xs font-semibold text-slate-300 flex items-center gap-2">
            <Palette className="w-4 h-4 text-cyan-400" />
            <span>Occasion Category</span>
          </label>
          <div className="flex flex-wrap gap-2">
            {['All', 'Formal', 'Evening', 'Casual', 'Active'].map(cat => (
              <button
                key={cat}
                onClick={() => setSelectedOccasion(cat)}
                className={`px-3.5 py-1.5 rounded-lg text-xs font-medium transition-all ${
                  selectedOccasion === cat
                    ? 'bg-cyan-600 text-white font-bold shadow-md shadow-cyan-600/30'
                    : 'bg-slate-900/60 text-slate-400 hover:text-white hover:bg-slate-800'
                }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>

      </div>

      {/* Recommendations Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {recommendations.map((outfit, index) => (
          <div
            key={outfit.id}
            className="glass-card rounded-2xl overflow-hidden border border-white/10 flex flex-col justify-between group hover:border-violet-500/40 transition-all"
          >
            <div>
              {/* Card Image Header */}
              <div className="relative h-64 overflow-hidden bg-slate-950">
                <img
                  src={outfit.image}
                  alt={outfit.name}
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                />

                <div className="absolute top-3 left-3 px-3 py-1 rounded-full glass-panel border border-violet-500/40 text-violet-300 text-xs font-bold flex items-center gap-1.5">
                  <Sparkles className="w-3.5 h-3.5 text-rose-400" />
                  <span>{outfit.compatibility_score}% AI Synergy</span>
                </div>

                <div className="absolute bottom-3 right-3 px-3 py-1 rounded-full bg-slate-950/80 text-white text-xs font-bold border border-white/10">
                  ${outfit.price}
                </div>
              </div>

              {/* Card Details */}
              <div className="p-5 space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-[11px] font-bold text-violet-400 uppercase tracking-wider">{outfit.category}</span>
                  {outfit.gender && <span className="text-[10px] text-slate-400">{outfit.gender}</span>}
                </div>

                <h3 className="font-serif text-lg font-bold text-white group-hover:text-violet-300 transition-colors">
                  {outfit.name}
                </h3>

                <p className="text-xs text-slate-300 line-clamp-2 leading-relaxed">
                  {outfit.description}
                </p>

                {/* Color Palette Swatches */}
                <div className="flex items-center gap-2 pt-1">
                  <span className="text-[10px] text-slate-400">Palette:</span>
                  <div className="flex items-center gap-1">
                    {outfit.color_palette.map((color, i) => (
                      <span
                        key={i}
                        className="w-3.5 h-3.5 rounded-full border border-white/20"
                        style={{ backgroundColor: color }}
                        title={color}
                      />
                    ))}
                  </div>
                </div>

                {/* Style Tags */}
                <div className="flex flex-wrap gap-1.5 pt-1">
                  {outfit.style_tags.map(tag => (
                    <span key={tag} className="px-2 py-0.5 rounded text-[9px] font-medium bg-slate-800 text-slate-300">
                      #{tag}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Card Action */}
            <div className="p-5 pt-0">
              <button
                onClick={() => setActiveTab('try-on')}
                className="w-full py-2.5 rounded-xl bg-gradient-to-r from-violet-600 to-rose-500 text-white font-semibold text-xs flex items-center justify-center gap-2 hover:opacity-90 transition-opacity"
              >
                <span>Try On This Recommendation</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            </div>

          </div>
        ))}
      </div>

    </section>
  );
};
